### ISSUE TITLE
öppettider & kontakt (design & JS) - 1p

### ISSUE THREAD

**Issue by holst9559** [3xer/SundsvallsSpegeln#10]
-Ska öppnas på en ny sida (content.html)
-Header och footer samma som startsidan
-Body ska bytas ut med innerHTML

-Ska innehålla:
  -Öppettider
  -Kontaktinformation (personer/telefonnummer)
  -Eventinformation

**Comment by PatSCoder** [comment]
This card have merge conflicts.
